### ISSUE TITLE
atomType sometimes is an array others a string

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmr-correlation#7]
@michaelwenk what do you think about fix the type to array even for mono dimensional experiments. Or is there a reason to this switch?

**Comment by michaelwenk** [comment]
@jobo322 What do you mean exactly?

**Comment by jobo322** [comment]
I mean that in the correlation data the property atomType sometimes is an array. e.g
![image](https://user-images.githubusercontent.com/12143935/125470024-d7d09634-df8a-4b6d-9bc4-849bb337d077.png)
![image](https://user-images.githubusercontent.com/12143935/125470055-f7870ed7-630c-4acb-9d3c-df0e9efc9eb7.png)
